FROM golang:1.4.2-cross

ENV GOOS linux
ENV GOPATH /usr/src/app

WORKDIR /usr/src/app

COPY . src/resin-supervisor

RUN chmod +x src/resin-supervisor/build_gosuper.sh

# Run go install with -a (force rebuilding of all packages)
# and -v (print package names as they are built)
CMD cd ./src/resin-supervisor && ./build_gosuper.sh
