version: '2.3'

services:
  # This service can only be named `main`, `balena-supervisor` or `core`
  # in a multi-container supervisor, the API `supervisor_release` needs to be able to
  # identify the "main" supervisor image so the `update-balena-supervisor` script works
  # properly
  core:
    build: ./
    privileged: true
    tty: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.dbus: '1'
      io.balena.features.balena-socket: '1'
