# Minimal runtime image
FROM resin/%%ARCH%%-supervisor-base:20160913

WORKDIR /usr/src/app

COPY ./build/%%ARCH%%/src ./src
COPY ./build/%%ARCH%%/node_modules ./node_modules
COPY ./build/%%ARCH%%/gosuper ./gosuper
COPY ./build/%%ARCH%%/rootfs-overlay/ /

VOLUME /data

ENV CONFIG_MOUNT_POINT /boot/config.json \
	LED_FILE /dev/null \
	SUPERVISOR_IMAGE resin/%%ARCH%%-supervisor

CMD [ "/sbin/init" ]

# -*- mode: dockerfile -*-
# vi: set ft=dockerfile :
