# Minimal runtime image
FROM %%BASE_IMAGE_TAG%%

WORKDIR /usr/src/app

COPY ./build/%%ARCH%%/src ./src
COPY ./build/%%ARCH%%/node_modules ./node_modules
COPY ./build/%%ARCH%%/rustsuper ./rustsuper
COPY ./build/%%ARCH%%/rootfs-overlay/ /

VOLUME /data

ENV CONFIG_MOUNT_POINT=/boot/config.json \
	LED_FILE=/dev/null \
	SUPERVISOR_IMAGE=resin/%%ARCH%%-supervisor

CMD [ "/sbin/init" ]

# -*- mode: dockerfile -*-
# vi: set ft=dockerfile :
