FROM dockerfile/nodejs

ADD . /app

WORKDIR /app

ENV SUPERVISOR_IMAGE resin/x86_64-supervisor
ENV CONFIG_MOUNT_POINT /boot/config.json
ENV LED_FILE /dev/null

RUN rm -rf node_modules
RUN npm install --unsafe-perm --production

RUN ln -sf /app/entry.sh /start

RUN apt-get clean

CMD ["/app/entry.sh"]
