# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'Finalize releases on staging'
description: 'Custom publish step to finalize releases on balena staging'
# these inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: 'JSON stringified object containing all the inputs from the calling workflow'
    required: true
  secrets:
    description: 'JSON stringified object containing all the secrets from the calling workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: balena-io/deploy-to-balena-action@4495424a8247c08911413a57afbbc62815a39e56 # v1.0.3
      with:
        balena_token: ${{ fromJSON(inputs.secrets).BALENA_STAGING_TOKEN }}
        fleet: ${{ env.matrix_value }}
        environment: balena-staging.com
        versionbot: false # ignore versionbot branch since the flowzone source is already versioned
        source: .
