name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]
jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@b16c072ba57dae80dcf72b13125ed6f1f60cff4f
    # prevent duplicate workflows and only allow one `pull_request` or `pull_request_target` for
    # internal or external contributions respectively
    if: |
      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target')
    secrets: inherit
    with:
      restrict_custom_actions: false
      balena_slugs: |
        balena_os/aarch64-supervisor,
        balena_os/amd64-supervisor,
        balena_os/armv7hf-supervisor,
        balena_os/i386-supervisor,
        balena_os/rpi-supervisor
      custom_publish_matrix: balena_os/aarch64-supervisor, balena_os/amd64-supervisor, balena_os/armv7hf-supervisor, balena_os/i386-supervisor, balena_os/rpi-supervisor
      custom_finalize_matrix: balena_os/aarch64-supervisor, balena_os/amd64-supervisor, balena_os/armv7hf-supervisor, balena_os/i386-supervisor, balena_os/rpi-supervisor
      protect_branch: false
